### ISSUE TITLE
Does not remember tab states after restart

### ISSUE THREAD

**Issue by campuscodi** [ktakayama/faviconizetab#13]
Whenever I restart my browser, tabs that were faviconized will be expanded again.

It appears to be doing this only for recently faviconized tabs, not for the old ones. I have very old faviconized tabs saved in other tab groups which still remember their minimized state. Only the newly minimized tabs seem to have this problem.

**Comment by DrLightman** [comment]
Any idea how to fix this?

**Comment by campuscodi** [comment]
Fix is here. https://github.com/mklishevych/faviconizetab/releases/download/fix-remember-state-on-restart/faviconize-tab.xpi

Works fine in Firefox 42

**Comment by DrLightman** [comment]
Installed, thank you very much! Too bad it doesn't make its way into official Moz repo.
